<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>clarity</string>
    <key>scopeName</key>
    <string>source.clar</string>
    <key>uuid</key>
    <string>f9e9871d-2ea6-4be0-afd2-fc382d704716</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#datatype</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keyword</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#number</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#string</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#define</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#lang-func</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#tuple-key</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>name</key>
        <string>comment.line.semicolon.clarity</string>
        <key>match</key>
        <string>(?x) (?&lt;=^|[()\[\]{}",'`;\s]) (;) .* $</string>
      </dict>
      <key>datatype</key>
      <dict>
        <key>name</key>
        <string>storage.type.clarity</string>
        <key>match</key>
        <string>(?x)
(?&lt;=^|[\s:(){},])
(tuple|list|response|optional|buff|string-ascii|string-utf8|principal|bool|int|uint)
(?=[\s(){},])</string>
      </dict>
      <key>keyword</key>
      <dict>
        <key>name</key>
        <string>constant.language.clarity</string>
        <key>match</key>
        <string>(?x)
  (?&lt;=^|[\s:(){},]) 
  (?:block-height|burn-block-height|contract-caller|false|is-in-regtest|none|stx-liquid-supply|true|tx-sender)
  (?=[\s(){},])
</string>
      </dict>
      <key>number</key>
      <dict>
        <key>name</key>
        <string>constant.numeric.clarity</string>
        <key>match</key>
        <string>(?x)
  (?&lt;=^|[\s:(){},])
  \'[0-9A-Z]{28,41}(:?\.[a-zA-Z][a-zA-Z0-9\-]+){0,2}|
  0x[0-9a-f]{2,}|
  u[0-9]+|
  [0-9]+
  (?=[\s(){},]|$)
</string>
      </dict>
      <key>string</key>
      <dict>
        <key>name</key>
        <string>string.quoted.double.clarity</string>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <array>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.clarity</string>
            </dict>
          </array>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <array>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.clarity</string>
            </dict>
          </array>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#escape-char</string>
          </dict>
        </array>
      </dict>
      <key>escape-char</key>
      <dict>
        <key>name</key>
        <string>constant.character.escape.clarity</string>
        <key>match</key>
        <string>\\.</string>
      </dict>
      <key>lang-func</key>
      <dict>
        <key>match</key>
        <string>(?x)
  (?&lt;=^|[(]) \s*
  (
    and|append|as-contract|as-max-len\?|asserts!|at-block|begin|concat|contract-call\?|contract-of|
    default-to|element-at|err|filter|fold|ft-burn\?|ft-get-balance|ft-get-supply|ft-mint\?|ft-transfer\?|
    get|get-block-info\?|hash160|if|impl-trait|index-of|is-eq|is-err|is-none|is-ok|is-some|keccak256|
    len|let|list|log2|map|map-delete|map-get\?|map-insert|map-set|match|merge|mod|nft-burn\?|nft-get-owner\?|
    nft-mint\?|nft-transfer\?|not|ok|or|pow|principal-of\?|print|secp256k1-recover\?|secp256k1-verify|sha256|
    sha512|sha512/256|some|sqrti|stx-burn\?|stx-get-balance|stx-transfer\?|to-int|to-uint|try!|unwrap-err-panic|
    unwrap-err!|unwrap-panic|unwrap!|var-get|var-set|xor
  ) \s+
</string>
        <key>name</key>
        <string>keyword.control.clarity</string>
      </dict>
      <key>define</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#define-func</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#define-var</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#set-func</string>
          </dict>
        </array>
      </dict>
      <key>set-func</key>
      <dict>
        <key>begin</key>
        <string>(?x)
  (?&lt;=^|[(]) \s*
  (var-get|var-set|map-get\?|map-set|map-insert|get) \s+
  ([a-z][a-zA-Z0-9_-]+) \s*
</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.clarity</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.clarity</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.end.clarity</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#lang-func</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#tuple-key</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number</string>
          </dict>
        </array>
      </dict>
      <key>define-func</key>
      <dict>
        <key>begin</key>
        <string>(?x)
  (?&lt;=^|[(]) \s*
  (define-(?:public|private|read-only)) \s+
  (\() \s*
  ([a-z][a-zA-Z0-9_-]+) \s*
</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.clarity</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.begin.clarity</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.clarity</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.end.clarity</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#args</string>
          </dict>
        </array>
      </dict>
      <key>define-var</key>
      <dict>
        <key>match</key>
        <string>(?x)
  (?&lt;=^[(]) \s*
  (define-(?:constant|data-var|map|fungible-token|non-fungible-token|trait)) \s+
  ([a-zA-Z][a-zA-Z0-9_-]+)
</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.clarity</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.clarity</string>
          </dict>
        </dict>
      </dict>
      <key>tuple-key</key>
      <dict>
        <key>name</key>
        <string>entity.name.type.clarity</string>
        <key>match</key>
        <string>(?x)
  ([a-z][a-zA-Z0-9_-]+)(?=:)
</string>
      </dict>
      <key>args</key>
      <dict>
        <key>begin</key>
        <string>(?x)
  (?&lt;=^|[(]) \s*
  ([a-z][a-zA-Z0-9_-]+) \s*
</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.clarity</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.end.clarity</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#datatype</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#tuple-key</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>